/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InsideAdminDB;

import InternalPackage.Dashboard;
import config.dbconnect;
import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author SCC-COLLEGE
 */
public class EditUsers extends javax.swing.JFrame {

    /**
     * Creates new form EditUsers
     */
     List<String> existingEmails = Arrays.asList("cs_email");
    public EditUsers() {
        initComponents();
    }
    Color hover = new Color(153,153,153);  
    Color defbutton = new Color(102,102,102);  
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void resetButtonColor(JButton button){
        button.setBackground(defbutton);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        add_contact = new javax.swing.JTextField();
        add_email = new javax.swing.JTextField();
        add_fname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        canedit = new javax.swing.JButton();
        RegDoneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("EDIT USERS FORM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 290, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_contact.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add_contact.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        add_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_contactActionPerformed(evt);
            }
        });
        jPanel3.add(add_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        add_email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add_email.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        add_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_emailActionPerformed(evt);
            }
        });
        jPanel3.add(add_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 240, 50));

        add_fname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add_fname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        add_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_fnameActionPerformed(evt);
            }
        });
        jPanel3.add(add_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 50));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("First Name*");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Email Address*");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Status*");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        status.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        status.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 240, 50));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Contact Number*");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, 340));

        canedit.setBackground(new java.awt.Color(102, 102, 102));
        canedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        canedit.setText("Cancel");
        canedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                caneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caneditMouseExited(evt);
            }
        });
        canedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caneditActionPerformed(evt);
            }
        });
        jPanel1.add(canedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 128, 49));

        RegDoneButton.setBackground(new java.awt.Color(102, 102, 102));
        RegDoneButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegDoneButton.setText("Update");
        RegDoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegDoneButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegDoneButtonMouseExited(evt);
            }
        });
        RegDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegDoneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegDoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 128, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_contactActionPerformed

    private void add_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_emailActionPerformed

    private void add_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_fnameActionPerformed

    }//GEN-LAST:event_add_fnameActionPerformed

    private void caneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caneditMouseEntered
        canedit.setBackground(hover);
    }//GEN-LAST:event_caneditMouseEntered

    private void caneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caneditMouseExited
        canedit.setBackground(defbutton);
    }//GEN-LAST:event_caneditMouseExited

    private void caneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caneditActionPerformed

        Dashboard db = new Dashboard();
        this.dispose();
        db.setVisible(true);
    }//GEN-LAST:event_caneditActionPerformed

    private void RegDoneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegDoneButtonMouseEntered
        RegDoneButton.setBackground(hover);
    }//GEN-LAST:event_RegDoneButtonMouseEntered

    private void RegDoneButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegDoneButtonMouseExited
        RegDoneButton.setBackground(defbutton);
    }//GEN-LAST:event_RegDoneButtonMouseExited

    private void RegDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegDoneButtonActionPerformed
        dbconnect dbc = new dbconnect();
        boolean isValid = true;
        
        String emails = add_email.getText().trim();

        StringBuilder errorMessages = new StringBuilder();

        // First Name Validation

        if (add_fname.getText().isEmpty()) {
            add_fname.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("First name is required.\n");
            isValid = false;
        } else {
            add_fname.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

    

        // Email Validation
        if (add_email.getText().isEmpty()) {
            add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Email is required.\n");
            isValid = false;
        } else {
            add_email.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

        // Check if Email already exists in the list
        if (existingEmails.contains(add_email.getText())) {
            add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Email is already registered.\n");
            isValid = false;
        }

        // Email Format Validation
        if (!add_email.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")) {
            add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Email must be in the format 'username@domain.com'.\n");
            isValid = false;
        } else {
            add_email.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }


        // Contact Number Validation
        if (add_contact.getText().isEmpty()) {
            add_contact.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Contact number is required.\n");
            isValid = false;
        } else {
            add_contact.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

        String contactNumber = add_contact.getText().trim();
        if (!contactNumber.matches("\\d{11}")) {
            add_contact.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Contact number must contain exactly 11 digits.\n");
            isValid = false;
        } else {
            add_contact.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

      
        if (!isValid) {
            // Show all error messages in a single JOptionPane dialog
            JOptionPane.showMessageDialog(null, errorMessages.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Update Completed", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Database Insertion
           if (dbc.insertData("UPDATE customer SET cs_fname = '" + add_fname.getText() + "', "
                + "cs_email = '" + add_email.getText() + "', "
                + "cs_contact = '" + add_contact.getText() + "', "
                + "cs_status = 'Active' "
                + "WHERE cs_email = '" + add_email.getText() + "'") == 1) {

            Dashboard db = new Dashboard();
            this.dispose();
            db.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Database insertion failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_RegDoneButtonActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegDoneButton;
    public javax.swing.JTextField add_contact;
    public javax.swing.JTextField add_email;
    public javax.swing.JTextField add_fname;
    private javax.swing.JButton canedit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
