/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InsideManagerDB;

import InternalPackage.ManagersDB;
import config.Session;
import config.dbconnect;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Administrator
 */
public class FoodForm extends javax.swing.JFrame {

    /**
     * Creates new form FoodForm
     */
    public FoodForm() {
        initComponents();
    }
        
    private String selectedImageFilename = null;
    private File selectedFile = null;
   

    Color hover = new Color(153,153,153);  
    Color defbutton = new Color(102,102,102);  
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void resetButtonColor(JButton button){
        button.setBackground(defbutton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addbot = new javax.swing.JButton();
        canbot = new javax.swing.JButton();
        f_status = new javax.swing.JComboBox<>();
        f_name = new javax.swing.JTextField();
        f_price = new javax.swing.JTextField();
        f_cat = new javax.swing.JComboBox<>();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setText("Add Food To Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 50));

        addbot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addbot.setText("ADD");
        addbot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbotMouseExited(evt);
            }
        });
        addbot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbotActionPerformed(evt);
            }
        });
        jPanel3.add(addbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 110, 40));

        canbot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        canbot.setText("CANCEL");
        canbot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canbotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                canbotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canbotMouseExited(evt);
            }
        });
        canbot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbotActionPerformed(evt);
            }
        });
        jPanel3.add(canbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 110, 40));

        f_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        f_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose status", "Available", "Unavailable", " ", " " }));
        jPanel3.add(f_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 240, 60));

        f_name.setBackground(new java.awt.Color(153, 153, 153));
        f_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        f_name.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        f_name.setCaretColor(new java.awt.Color(255, 255, 255));
        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });
        jPanel3.add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, 70));

        f_price.setBackground(new java.awt.Color(153, 153, 153));
        f_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        f_price.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.add(f_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 70));

        f_cat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        f_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Category", "Meals", "Drinks", "Snacks", "Dessert" }));
        f_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_catActionPerformed(evt);
            }
        });
        jPanel3.add(f_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbotActionPerformed
       
     dbconnect dbc = new dbconnect();
        boolean isValid = true;
        StringBuilder errorMessages = new StringBuilder();

    // Get input values
    String foodName = f_name.getText().trim();
    String foodPriceText = f_price.getText().trim();
    String foodCategory = f_cat.getSelectedItem().toString().trim();                     
    String foodStatus = f_status.getSelectedItem().toString().trim();  

    // Validate Food Name
    if (foodName.isEmpty()) {
        f_name.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Food name is required.\n");
        isValid = false;
    } else {
        f_name.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Food Price
    double foodPrice = 0.0;
    try {
        foodPrice = Double.parseDouble(foodPriceText);
        if (foodPrice < 0) throw new NumberFormatException();
        f_price.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    } catch (NumberFormatException e) {
        f_price.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Enter a valid positive number for food price.\n");
        isValid = false;
    }

    // Validate Category
    if (f_cat.getSelectedIndex() == 0) {
        f_cat.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Please select a food category.\n");
        isValid = false;
    } else {
        f_cat.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Status
    if (f_status.getSelectedIndex() == 0) {
        f_status.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Please select a food status.\n");
        isValid = false;
    } else {
        f_status.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Show validation errors if any
    if (!isValid) {
        JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Insert into database
    try {
        Connection conn = dbc.getConnection();

        String sql = "INSERT INTO food_tbl (f_name, f_price, f_category, f_status, f_image) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        pst.setString(1, foodName);
        pst.setDouble(2, foodPrice);
        pst.setString(3, foodCategory);
        pst.setString(4, foodStatus);

        int rows = pst.executeUpdate();

        if (rows > 0) {
            ResultSet keys = pst.getGeneratedKeys();
            int lastId = -1;
            if (keys.next()) {
                lastId = keys.getInt(1);
            }

            // Log the action
            Session sess = Session.getInstance();
            String userId = sess.getUid();

            if (userId != null && !userId.trim().isEmpty()) {
                String actions = "Added New Food Item! ID: " + lastId;

                PreparedStatement logPst = conn.prepareStatement(
                    "INSERT INTO logs (id, actions, date) VALUES (?, ?, ?)"
                );
                logPst.setString(1, userId);
                logPst.setString(2, actions);
                logPst.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
                logPst.executeUpdate();
            } else {
                System.out.println("Warning: Session UID is null or empty. Log not inserted.");
            }

            JOptionPane.showMessageDialog(null, "Food item added successfully!");

            // Clear inputs
            f_name.setText("");
            f_price.setText("");
            f_cat.setSelectedIndex(0);
            f_status.setSelectedIndex(0);

            // Redirect to FoodsDB
            FoodsDB fdb = new FoodsDB();
            this.dispose();
            fdb.setVisible(true);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_addbotActionPerformed

    private void canbotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canbotActionPerformed

    private void addbotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbotMouseEntered
         addbot.setBackground(hover);
    }//GEN-LAST:event_addbotMouseEntered

    private void addbotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbotMouseExited
         addbot.setBackground(defbutton);
    }//GEN-LAST:event_addbotMouseExited

    private void canbotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbotMouseEntered
        canbot.setBackground(hover);
    }//GEN-LAST:event_canbotMouseEntered

    private void canbotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbotMouseExited
         canbot.setBackground(defbutton);
    }//GEN-LAST:event_canbotMouseExited

    private void canbotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbotMouseClicked
        ManagersDB mdb = new ManagersDB();
        mdb.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_canbotMouseClicked

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    private void f_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_catActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbot;
    private javax.swing.JButton canbot;
    private javax.swing.JComboBox<String> f_cat;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField f_price;
    private javax.swing.JComboBox<String> f_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
