/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForgotPassword;

import OutsidePackage.login;

/**
 *
 * @author Administrator
 */
public class NewPass extends javax.swing.JFrame {

    /**
     * Creates new form NewPass
     */
    public NewPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loghide1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        connewshow = new javax.swing.JLabel();
        connewhide = new javax.swing.JLabel();
        connewpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        newshow = new javax.swing.JLabel();
        newhide = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        loghide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/hideeye-removebg-preview (1).png"))); // NOI18N
        loghide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loghide1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loghide1MouseReleased(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Input New Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 270, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        connewshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/showeye-removebg-preview (2).png"))); // NOI18N
        jPanel3.add(connewshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        connewhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/hideeye-removebg-preview (1).png"))); // NOI18N
        connewhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connewhideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                connewhideMouseReleased(evt);
            }
        });
        jPanel3.add(connewhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        connewpass.setText("jPasswordField2");
        jPanel3.add(connewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 240, 70));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Confirm new password*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, 40));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setText("Save");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 40));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/showeye-removebg-preview (2).png"))); // NOI18N
        jPanel4.add(newshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        newhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/hideeye-removebg-preview (1).png"))); // NOI18N
        newhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newhideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newhideMouseReleased(evt);
            }
        });
        jPanel4.add(newhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        newpass.setText("jPasswordField1");
        jPanel4.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 240, 70));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("New password*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newhideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newhideMousePressed
        newshow.setVisible(true);
        newhide.setVisible(false);
        newpass.setEchoChar((char)0);
    }//GEN-LAST:event_newhideMousePressed

    private void newhideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newhideMouseReleased
        newshow.setVisible(false);
        newhide.setVisible(true);
        newpass.setEchoChar('*');
    }//GEN-LAST:event_newhideMouseReleased

    private void loghide1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loghide1MousePressed
        newshow.setVisible(true);
        newhide.setVisible(false);
        newpass.setEchoChar((char)0);
    }//GEN-LAST:event_loghide1MousePressed

    private void loghide1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loghide1MouseReleased
        newshow.setVisible(false);
        newhide.setVisible(true);
        newpass.setEchoChar('*');
    }//GEN-LAST:event_loghide1MouseReleased

    private void connewhideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connewhideMousePressed
        newshow.setVisible(true);
        newhide.setVisible(false);
        connewpass.setEchoChar((char)0);
    }//GEN-LAST:event_connewhideMousePressed

    private void connewhideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connewhideMouseReleased
        newshow.setVisible(false);
        newhide.setVisible(true);
        connewpass.setEchoChar('*');
    }//GEN-LAST:event_connewhideMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connewhide;
    private javax.swing.JPasswordField connewpass;
    private javax.swing.JLabel connewshow;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel loghide1;
    private javax.swing.JLabel newhide;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JLabel newshow;
    // End of variables declaration//GEN-END:variables
}
